name: Image build
on:
  push:
    branches:
    - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install fdisk gdisk qemu-user-static libarchive-tools tar

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Build image
        run: |
          docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm:latest build pi.json
          du -h output.img.xz

      - name: Save image artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: output.img.xz